/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ParceiroRouteImport } from './routes/parceiro'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as ParceiroPdvRouteImport } from './routes/parceiro.pdv'
import { Route as ParceiroLoginRouteImport } from './routes/parceiro.login'
import { Route as ParceiroDashboardRouteImport } from './routes/parceiro.dashboard'
import { Route as ParceiroCadastroRouteImport } from './routes/parceiro.cadastro'
import { Route as OrcamentoIdRouteImport } from './routes/orcamento.$id'
import { Route as DeclaracaoIdRouteImport } from './routes/declaracao.$id'
import { Route as AppVendedoresRouteImport } from './routes/app.vendedores'
import { Route as AppVendasParceirosRouteImport } from './routes/app.vendas-parceiros'
import { Route as AppVendasRouteImport } from './routes/app.vendas'
import { Route as AppVendaNovaRouteImport } from './routes/app.venda-nova'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppRegistroRouteImport } from './routes/app.registro'
import { Route as AppProdutosRouteImport } from './routes/app.produtos'
import { Route as AppProdutoNovoRouteImport } from './routes/app.produto-novo'
import { Route as AppPdvRouteImport } from './routes/app.pdv'
import { Route as AppNotificacoesRouteImport } from './routes/app.notificacoes'
import { Route as AppLogisticaRouteImport } from './routes/app.logistica'
import { Route as AppFornecedoresRouteImport } from './routes/app.fornecedores'
import { Route as AppFornecedorNovoRouteImport } from './routes/app.fornecedor-novo'
import { Route as AppFiscalRouteImport } from './routes/app.fiscal'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppEstoqueRouteImport } from './routes/app.estoque'
import { Route as AppDavNovoRouteImport } from './routes/app.dav-novo'
import { Route as AppDavRouteImport } from './routes/app.dav'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppComprasRouteImport } from './routes/app.compras'
import { Route as AppCompraNovaRouteImport } from './routes/app.compra-nova'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppClienteNovoRouteImport } from './routes/app.cliente-novo'
import { Route as AppCatalogoRouteImport } from './routes/app.catalogo'

const ParceiroRoute = ParceiroRouteImport.update({
  id: '/parceiro',
  path: '/parceiro',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ParceiroPdvRoute = ParceiroPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => ParceiroRoute,
} as any)
const ParceiroLoginRoute = ParceiroLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ParceiroRoute,
} as any)
const ParceiroDashboardRoute = ParceiroDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ParceiroRoute,
} as any)
const ParceiroCadastroRoute = ParceiroCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => ParceiroRoute,
} as any)
const OrcamentoIdRoute = OrcamentoIdRouteImport.update({
  id: '/orcamento/$id',
  path: '/orcamento/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DeclaracaoIdRoute = DeclaracaoIdRouteImport.update({
  id: '/declaracao/$id',
  path: '/declaracao/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVendedoresRoute = AppVendedoresRouteImport.update({
  id: '/vendedores',
  path: '/vendedores',
  getParentRoute: () => AppRoute,
} as any)
const AppVendasParceirosRoute = AppVendasParceirosRouteImport.update({
  id: '/vendas-parceiros',
  path: '/vendas-parceiros',
  getParentRoute: () => AppRoute,
} as any)
const AppVendasRoute = AppVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AppRoute,
} as any)
const AppVendaNovaRoute = AppVendaNovaRouteImport.update({
  id: '/venda-nova',
  path: '/venda-nova',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppRegistroRoute = AppRegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosRoute = AppProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutoNovoRoute = AppProdutoNovoRouteImport.update({
  id: '/produto-novo',
  path: '/produto-novo',
  getParentRoute: () => AppRoute,
} as any)
const AppPdvRoute = AppPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacoesRoute = AppNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppLogisticaRoute = AppLogisticaRouteImport.update({
  id: '/logistica',
  path: '/logistica',
  getParentRoute: () => AppRoute,
} as any)
const AppFornecedoresRoute = AppFornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => AppRoute,
} as any)
const AppFornecedorNovoRoute = AppFornecedorNovoRouteImport.update({
  id: '/fornecedor-novo',
  path: '/fornecedor-novo',
  getParentRoute: () => AppRoute,
} as any)
const AppFiscalRoute = AppFiscalRouteImport.update({
  id: '/fiscal',
  path: '/fiscal',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueRoute = AppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppRoute,
} as any)
const AppDavNovoRoute = AppDavNovoRouteImport.update({
  id: '/dav-novo',
  path: '/dav-novo',
  getParentRoute: () => AppRoute,
} as any)
const AppDavRoute = AppDavRouteImport.update({
  id: '/dav',
  path: '/dav',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppComprasRoute = AppComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AppRoute,
} as any)
const AppCompraNovaRoute = AppCompraNovaRouteImport.update({
  id: '/compra-nova',
  path: '/compra-nova',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppClienteNovoRoute = AppClienteNovoRouteImport.update({
  id: '/cliente-novo',
  path: '/cliente-novo',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogoRoute = AppCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/parceiro': typeof ParceiroRouteWithChildren
  '/app/catalogo': typeof AppCatalogoRoute
  '/app/cliente-novo': typeof AppClienteNovoRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/compra-nova': typeof AppCompraNovaRoute
  '/app/compras': typeof AppComprasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/dav': typeof AppDavRoute
  '/app/dav-novo': typeof AppDavNovoRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/fiscal': typeof AppFiscalRoute
  '/app/fornecedor-novo': typeof AppFornecedorNovoRoute
  '/app/fornecedores': typeof AppFornecedoresRoute
  '/app/logistica': typeof AppLogisticaRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/pdv': typeof AppPdvRoute
  '/app/produto-novo': typeof AppProdutoNovoRoute
  '/app/produtos': typeof AppProdutosRoute
  '/app/registro': typeof AppRegistroRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/venda-nova': typeof AppVendaNovaRoute
  '/app/vendas': typeof AppVendasRoute
  '/app/vendas-parceiros': typeof AppVendasParceirosRoute
  '/app/vendedores': typeof AppVendedoresRoute
  '/declaracao/$id': typeof DeclaracaoIdRoute
  '/orcamento/$id': typeof OrcamentoIdRoute
  '/parceiro/cadastro': typeof ParceiroCadastroRoute
  '/parceiro/dashboard': typeof ParceiroDashboardRoute
  '/parceiro/login': typeof ParceiroLoginRoute
  '/parceiro/pdv': typeof ParceiroPdvRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/parceiro': typeof ParceiroRouteWithChildren
  '/app/catalogo': typeof AppCatalogoRoute
  '/app/cliente-novo': typeof AppClienteNovoRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/compra-nova': typeof AppCompraNovaRoute
  '/app/compras': typeof AppComprasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/dav': typeof AppDavRoute
  '/app/dav-novo': typeof AppDavNovoRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/fiscal': typeof AppFiscalRoute
  '/app/fornecedor-novo': typeof AppFornecedorNovoRoute
  '/app/fornecedores': typeof AppFornecedoresRoute
  '/app/logistica': typeof AppLogisticaRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/pdv': typeof AppPdvRoute
  '/app/produto-novo': typeof AppProdutoNovoRoute
  '/app/produtos': typeof AppProdutosRoute
  '/app/registro': typeof AppRegistroRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/venda-nova': typeof AppVendaNovaRoute
  '/app/vendas': typeof AppVendasRoute
  '/app/vendas-parceiros': typeof AppVendasParceirosRoute
  '/app/vendedores': typeof AppVendedoresRoute
  '/declaracao/$id': typeof DeclaracaoIdRoute
  '/orcamento/$id': typeof OrcamentoIdRoute
  '/parceiro/cadastro': typeof ParceiroCadastroRoute
  '/parceiro/dashboard': typeof ParceiroDashboardRoute
  '/parceiro/login': typeof ParceiroLoginRoute
  '/parceiro/pdv': typeof ParceiroPdvRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/parceiro': typeof ParceiroRouteWithChildren
  '/app/catalogo': typeof AppCatalogoRoute
  '/app/cliente-novo': typeof AppClienteNovoRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/compra-nova': typeof AppCompraNovaRoute
  '/app/compras': typeof AppComprasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/dav': typeof AppDavRoute
  '/app/dav-novo': typeof AppDavNovoRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/fiscal': typeof AppFiscalRoute
  '/app/fornecedor-novo': typeof AppFornecedorNovoRoute
  '/app/fornecedores': typeof AppFornecedoresRoute
  '/app/logistica': typeof AppLogisticaRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/pdv': typeof AppPdvRoute
  '/app/produto-novo': typeof AppProdutoNovoRoute
  '/app/produtos': typeof AppProdutosRoute
  '/app/registro': typeof AppRegistroRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/venda-nova': typeof AppVendaNovaRoute
  '/app/vendas': typeof AppVendasRoute
  '/app/vendas-parceiros': typeof AppVendasParceirosRoute
  '/app/vendedores': typeof AppVendedoresRoute
  '/declaracao/$id': typeof DeclaracaoIdRoute
  '/orcamento/$id': typeof OrcamentoIdRoute
  '/parceiro/cadastro': typeof ParceiroCadastroRoute
  '/parceiro/dashboard': typeof ParceiroDashboardRoute
  '/parceiro/login': typeof ParceiroLoginRoute
  '/parceiro/pdv': typeof ParceiroPdvRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/catalogo'
    | '/parceiro'
    | '/app/catalogo'
    | '/app/cliente-novo'
    | '/app/clientes'
    | '/app/compra-nova'
    | '/app/compras'
    | '/app/configuracoes'
    | '/app/dashboard'
    | '/app/dav'
    | '/app/dav-novo'
    | '/app/estoque'
    | '/app/financeiro'
    | '/app/fiscal'
    | '/app/fornecedor-novo'
    | '/app/fornecedores'
    | '/app/logistica'
    | '/app/notificacoes'
    | '/app/pdv'
    | '/app/produto-novo'
    | '/app/produtos'
    | '/app/registro'
    | '/app/relatorios'
    | '/app/venda-nova'
    | '/app/vendas'
    | '/app/vendas-parceiros'
    | '/app/vendedores'
    | '/declaracao/$id'
    | '/orcamento/$id'
    | '/parceiro/cadastro'
    | '/parceiro/dashboard'
    | '/parceiro/login'
    | '/parceiro/pdv'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/parceiro'
    | '/app/catalogo'
    | '/app/cliente-novo'
    | '/app/clientes'
    | '/app/compra-nova'
    | '/app/compras'
    | '/app/configuracoes'
    | '/app/dashboard'
    | '/app/dav'
    | '/app/dav-novo'
    | '/app/estoque'
    | '/app/financeiro'
    | '/app/fiscal'
    | '/app/fornecedor-novo'
    | '/app/fornecedores'
    | '/app/logistica'
    | '/app/notificacoes'
    | '/app/pdv'
    | '/app/produto-novo'
    | '/app/produtos'
    | '/app/registro'
    | '/app/relatorios'
    | '/app/venda-nova'
    | '/app/vendas'
    | '/app/vendas-parceiros'
    | '/app/vendedores'
    | '/declaracao/$id'
    | '/orcamento/$id'
    | '/parceiro/cadastro'
    | '/parceiro/dashboard'
    | '/parceiro/login'
    | '/parceiro/pdv'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/catalogo'
    | '/parceiro'
    | '/app/catalogo'
    | '/app/cliente-novo'
    | '/app/clientes'
    | '/app/compra-nova'
    | '/app/compras'
    | '/app/configuracoes'
    | '/app/dashboard'
    | '/app/dav'
    | '/app/dav-novo'
    | '/app/estoque'
    | '/app/financeiro'
    | '/app/fiscal'
    | '/app/fornecedor-novo'
    | '/app/fornecedores'
    | '/app/logistica'
    | '/app/notificacoes'
    | '/app/pdv'
    | '/app/produto-novo'
    | '/app/produtos'
    | '/app/registro'
    | '/app/relatorios'
    | '/app/venda-nova'
    | '/app/vendas'
    | '/app/vendas-parceiros'
    | '/app/vendedores'
    | '/declaracao/$id'
    | '/orcamento/$id'
    | '/parceiro/cadastro'
    | '/parceiro/dashboard'
    | '/parceiro/login'
    | '/parceiro/pdv'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CatalogoRoute: typeof CatalogoRoute
  ParceiroRoute: typeof ParceiroRouteWithChildren
  DeclaracaoIdRoute: typeof DeclaracaoIdRoute
  OrcamentoIdRoute: typeof OrcamentoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/parceiro': {
      id: '/parceiro'
      path: '/parceiro'
      fullPath: '/parceiro'
      preLoaderRoute: typeof ParceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/parceiro/pdv': {
      id: '/parceiro/pdv'
      path: '/pdv'
      fullPath: '/parceiro/pdv'
      preLoaderRoute: typeof ParceiroPdvRouteImport
      parentRoute: typeof ParceiroRoute
    }
    '/parceiro/login': {
      id: '/parceiro/login'
      path: '/login'
      fullPath: '/parceiro/login'
      preLoaderRoute: typeof ParceiroLoginRouteImport
      parentRoute: typeof ParceiroRoute
    }
    '/parceiro/dashboard': {
      id: '/parceiro/dashboard'
      path: '/dashboard'
      fullPath: '/parceiro/dashboard'
      preLoaderRoute: typeof ParceiroDashboardRouteImport
      parentRoute: typeof ParceiroRoute
    }
    '/parceiro/cadastro': {
      id: '/parceiro/cadastro'
      path: '/cadastro'
      fullPath: '/parceiro/cadastro'
      preLoaderRoute: typeof ParceiroCadastroRouteImport
      parentRoute: typeof ParceiroRoute
    }
    '/orcamento/$id': {
      id: '/orcamento/$id'
      path: '/orcamento/$id'
      fullPath: '/orcamento/$id'
      preLoaderRoute: typeof OrcamentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/declaracao/$id': {
      id: '/declaracao/$id'
      path: '/declaracao/$id'
      fullPath: '/declaracao/$id'
      preLoaderRoute: typeof DeclaracaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/vendedores': {
      id: '/app/vendedores'
      path: '/vendedores'
      fullPath: '/app/vendedores'
      preLoaderRoute: typeof AppVendedoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vendas-parceiros': {
      id: '/app/vendas-parceiros'
      path: '/vendas-parceiros'
      fullPath: '/app/vendas-parceiros'
      preLoaderRoute: typeof AppVendasParceirosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vendas': {
      id: '/app/vendas'
      path: '/vendas'
      fullPath: '/app/vendas'
      preLoaderRoute: typeof AppVendasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/venda-nova': {
      id: '/app/venda-nova'
      path: '/venda-nova'
      fullPath: '/app/venda-nova'
      preLoaderRoute: typeof AppVendaNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/registro': {
      id: '/app/registro'
      path: '/registro'
      fullPath: '/app/registro'
      preLoaderRoute: typeof AppRegistroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/produtos': {
      id: '/app/produtos'
      path: '/produtos'
      fullPath: '/app/produtos'
      preLoaderRoute: typeof AppProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/produto-novo': {
      id: '/app/produto-novo'
      path: '/produto-novo'
      fullPath: '/app/produto-novo'
      preLoaderRoute: typeof AppProdutoNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pdv': {
      id: '/app/pdv'
      path: '/pdv'
      fullPath: '/app/pdv'
      preLoaderRoute: typeof AppPdvRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notificacoes': {
      id: '/app/notificacoes'
      path: '/notificacoes'
      fullPath: '/app/notificacoes'
      preLoaderRoute: typeof AppNotificacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logistica': {
      id: '/app/logistica'
      path: '/logistica'
      fullPath: '/app/logistica'
      preLoaderRoute: typeof AppLogisticaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fornecedores': {
      id: '/app/fornecedores'
      path: '/fornecedores'
      fullPath: '/app/fornecedores'
      preLoaderRoute: typeof AppFornecedoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fornecedor-novo': {
      id: '/app/fornecedor-novo'
      path: '/fornecedor-novo'
      fullPath: '/app/fornecedor-novo'
      preLoaderRoute: typeof AppFornecedorNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fiscal': {
      id: '/app/fiscal'
      path: '/fiscal'
      fullPath: '/app/fiscal'
      preLoaderRoute: typeof AppFiscalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estoque': {
      id: '/app/estoque'
      path: '/estoque'
      fullPath: '/app/estoque'
      preLoaderRoute: typeof AppEstoqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dav-novo': {
      id: '/app/dav-novo'
      path: '/dav-novo'
      fullPath: '/app/dav-novo'
      preLoaderRoute: typeof AppDavNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dav': {
      id: '/app/dav'
      path: '/dav'
      fullPath: '/app/dav'
      preLoaderRoute: typeof AppDavRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compras': {
      id: '/app/compras'
      path: '/compras'
      fullPath: '/app/compras'
      preLoaderRoute: typeof AppComprasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compra-nova': {
      id: '/app/compra-nova'
      path: '/compra-nova'
      fullPath: '/app/compra-nova'
      preLoaderRoute: typeof AppCompraNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cliente-novo': {
      id: '/app/cliente-novo'
      path: '/cliente-novo'
      fullPath: '/app/cliente-novo'
      preLoaderRoute: typeof AppClienteNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/catalogo': {
      id: '/app/catalogo'
      path: '/catalogo'
      fullPath: '/app/catalogo'
      preLoaderRoute: typeof AppCatalogoRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCatalogoRoute: typeof AppCatalogoRoute
  AppClienteNovoRoute: typeof AppClienteNovoRoute
  AppClientesRoute: typeof AppClientesRoute
  AppCompraNovaRoute: typeof AppCompraNovaRoute
  AppComprasRoute: typeof AppComprasRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDavRoute: typeof AppDavRoute
  AppDavNovoRoute: typeof AppDavNovoRoute
  AppEstoqueRoute: typeof AppEstoqueRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppFiscalRoute: typeof AppFiscalRoute
  AppFornecedorNovoRoute: typeof AppFornecedorNovoRoute
  AppFornecedoresRoute: typeof AppFornecedoresRoute
  AppLogisticaRoute: typeof AppLogisticaRoute
  AppNotificacoesRoute: typeof AppNotificacoesRoute
  AppPdvRoute: typeof AppPdvRoute
  AppProdutoNovoRoute: typeof AppProdutoNovoRoute
  AppProdutosRoute: typeof AppProdutosRoute
  AppRegistroRoute: typeof AppRegistroRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppVendaNovaRoute: typeof AppVendaNovaRoute
  AppVendasRoute: typeof AppVendasRoute
  AppVendasParceirosRoute: typeof AppVendasParceirosRoute
  AppVendedoresRoute: typeof AppVendedoresRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCatalogoRoute: AppCatalogoRoute,
  AppClienteNovoRoute: AppClienteNovoRoute,
  AppClientesRoute: AppClientesRoute,
  AppCompraNovaRoute: AppCompraNovaRoute,
  AppComprasRoute: AppComprasRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDavRoute: AppDavRoute,
  AppDavNovoRoute: AppDavNovoRoute,
  AppEstoqueRoute: AppEstoqueRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppFiscalRoute: AppFiscalRoute,
  AppFornecedorNovoRoute: AppFornecedorNovoRoute,
  AppFornecedoresRoute: AppFornecedoresRoute,
  AppLogisticaRoute: AppLogisticaRoute,
  AppNotificacoesRoute: AppNotificacoesRoute,
  AppPdvRoute: AppPdvRoute,
  AppProdutoNovoRoute: AppProdutoNovoRoute,
  AppProdutosRoute: AppProdutosRoute,
  AppRegistroRoute: AppRegistroRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppVendaNovaRoute: AppVendaNovaRoute,
  AppVendasRoute: AppVendasRoute,
  AppVendasParceirosRoute: AppVendasParceirosRoute,
  AppVendedoresRoute: AppVendedoresRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ParceiroRouteChildren {
  ParceiroCadastroRoute: typeof ParceiroCadastroRoute
  ParceiroDashboardRoute: typeof ParceiroDashboardRoute
  ParceiroLoginRoute: typeof ParceiroLoginRoute
  ParceiroPdvRoute: typeof ParceiroPdvRoute
}

const ParceiroRouteChildren: ParceiroRouteChildren = {
  ParceiroCadastroRoute: ParceiroCadastroRoute,
  ParceiroDashboardRoute: ParceiroDashboardRoute,
  ParceiroLoginRoute: ParceiroLoginRoute,
  ParceiroPdvRoute: ParceiroPdvRoute,
}

const ParceiroRouteWithChildren = ParceiroRoute._addFileChildren(
  ParceiroRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CatalogoRoute: CatalogoRoute,
  ParceiroRoute: ParceiroRouteWithChildren,
  DeclaracaoIdRoute: DeclaracaoIdRoute,
  OrcamentoIdRoute: OrcamentoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
